name: CI

on:
  push:
    branches:
      - main # Passe dies an, um die relevante Hauptentwicklungsbranch anzugeben

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Clean and Build
        run: ./gradlew clean build --info --stacktrace

